name: Java CI
on: push
env:
  docker_username: ${{ secrets.DOCKER_USERNAME }}
  docker_password: ${{ secrets.DOCKER_PASSWORD }}
jobs:
  Clone-down:
    name: Clone-down
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - uses: actions/checkout@v2
      - name: Upload Repo
        uses: actions/upload-artifact@v2
        with:
            name: code
            path: .
  Build:
    name: Build
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
            name: code
            path: .
      - name: Permission granted
        run: chmod +x ./ci/build-app.sh
      - name: my-step
        run: ./ci/build-app.sh
      - name: Upload Buildcode
        uses: actions/upload-artifact@v2
        with:
            name: buildcode
            path: .
    needs: Clone-down
  Test:
    name: Test
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Download repo
        uses: actions/download-artifact@v2
        with:
          name: code
          path: .
      - name: Permission granted
        run: chmod +x ./ci/unit-test-app.sh
      - name: Test
        run: ./ci/unit-test-app.sh
    needs: Clone-down
  Docker-image:
    name: Docker-image
    runs-on: ubuntu-latest
    needs:
      - Test
      - Build
    steps:
      - name: Download buildcode
        uses: actions/download-artifact@v2
        with:
            name: buildcode
            path: .
      - name: build image
        run: chmod +x ./ci/build-docker.sh && ./ci/build-docker.sh
      - name: push image
        run: chmod +x ./ci/push-docker.sh && ./ci/push-docker.sh && export GIT_COMMIT="GA-$GITHUB_SHA"
  Component-test:
    name: Component-test
    runs-on: ubuntu-latest
    needs: Docker-image
    steps:
      - name: Download buildcode
        uses: actions/download-artifact@v2
        with:
            name: buildcode
            path: .
      - name: CompTest
        run: chmod +x ./ci/component-test.sh && export GIT_COMMIT="GA-$GITHUB_SHA" && ./ci/component-test.sh
  
